export const DATA_SCOPES = Object.freeze({
  ONLY_ASSIGNED_CLIENTS: 'ONLY_ASSIGNED_CLIENTS',
  ALL_CLIENTS: 'ALL_CLIENTS',
  ASSIGNED_ORDERS: 'ASSIGNED_ORDERS',
  ALL_ORDERS: 'ALL_ORDERS',
  OWN_DATA: 'OWN_DATA',
  ALL_DATA: 'ALL_DATA',
});

export const CLIENT_SCOPE_OPTIONS = [DATA_SCOPES.ONLY_ASSIGNED_CLIENTS, DATA_SCOPES.ALL_CLIENTS];
export const ORDER_SCOPE_OPTIONS = [DATA_SCOPES.ASSIGNED_ORDERS, DATA_SCOPES.ALL_ORDERS];
