/**
 * Mirrors backend/src/constants/permissions.js. Kept in sync manually
 * for Phase 0; worth generating from a shared package in a later phase
 * if the duplication becomes painful.
 */
export const PERMISSIONS = Object.freeze({
  VIEW_CLIENT: 'VIEW_CLIENT',
  CREATE_CLIENT: 'CREATE_CLIENT',
  EDIT_CLIENT: 'EDIT_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  ASSIGN_CLIENT: 'ASSIGN_CLIENT',
  REASSIGN_CLIENT: 'REASSIGN_CLIENT',

  VIEW_ORDER: 'VIEW_ORDER',
  CREATE_ORDER: 'CREATE_ORDER',
  EDIT_ORDER: 'EDIT_ORDER',
  ASSIGN_ORDER: 'ASSIGN_ORDER',
  REASSIGN_ORDER: 'REASSIGN_ORDER',
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  CLOSE_ORDER: 'CLOSE_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',

  VIEW_KYC: 'VIEW_KYC',
  UPLOAD_KYC: 'UPLOAD_KYC',
  VERIFY_KYC: 'VERIFY_KYC',
  REJECT_KYC: 'REJECT_KYC',
  DOWNLOAD_KYC: 'DOWNLOAD_KYC',
  DELETE_KYC: 'DELETE_KYC',

  VIEW_PAYMENT: 'VIEW_PAYMENT',
  VIEW_PAYMENT_DETAILS: 'VIEW_PAYMENT_DETAILS',
  REFUND_PAYMENT: 'REFUND_PAYMENT',

  VIEW_SERVICE: 'VIEW_SERVICE',
  CREATE_SERVICE: 'CREATE_SERVICE',
  EDIT_SERVICE: 'EDIT_SERVICE',
  DELETE_SERVICE: 'DELETE_SERVICE',

  VIEW_ADMINS: 'VIEW_ADMINS',
  CREATE_ADMIN: 'CREATE_ADMIN',
  EDIT_ADMIN: 'EDIT_ADMIN',
  DISABLE_ADMIN: 'DISABLE_ADMIN',
  MANAGE_ADMIN_PERMISSIONS: 'MANAGE_ADMIN_PERMISSIONS',
  ASSIGN_ADMIN_CLIENTS: 'ASSIGN_ADMIN_CLIENTS',

  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',

  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

  VIEW_SETTINGS: 'VIEW_SETTINGS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',

  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',

  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  VIEW_OWN_ORDERS: 'VIEW_OWN_ORDERS',
  VIEW_OWN_DOCUMENTS: 'VIEW_OWN_DOCUMENTS',
  UPLOAD_OWN_DOCUMENTS: 'UPLOAD_OWN_DOCUMENTS',
  VIEW_OWN_NOTIFICATIONS: 'VIEW_OWN_NOTIFICATIONS',
});
