export const SERVICE_CATEGORY = Object.freeze({
  WEBSITE: 'WEBSITE',
  WHATSAPP: 'WHATSAPP',
  CRM: 'CRM',
  HRMS: 'HRMS',
  SOFTWARE: 'SOFTWARE',
  DIGITAL_MARKETING: 'DIGITAL_MARKETING',
  OTHER: 'OTHER',
});

export const ALL_SERVICE_CATEGORIES = Object.values(SERVICE_CATEGORY);
